---
version: '3'
services:
  # Database
  jme-message-contract-db-local:
    image: postgres:17.7
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=jme-messagecontract
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=jme-messagecontract-db-local
